### ISSUE TITLE
连接出错，请添加passb参数后重新运行

### ISSUE THREAD

**Issue by FeiNiao** [novysodope/yonyou_check#1]
连接出错，请添加passb参数后重新运行，这个参数是在哪里添加？

**Comment by novysodope** [comment]
随便哪里输入passb都行 

-u http://xxx.xxx.xxx passb

or

passb -u http://xxx.xxx.xxx

**Comment by novysodope** [comment]
如果还不行的话请下载最新版本添加参数运行，有一个版本代码里我记得是参数写错了，后面修正了( ´ ▽ ` )

**Comment by FeiNiao** [comment]
![image](https://github.com/novysodope/fupo_for_yonyou/assets/66779835/9fa34d62-a517-45b5-bbc6-f2bbf90b5ebd)

还是不行，最新版的win和Linux都试过了

**Comment by novysodope** [comment]
好像的确是的，等下我看看

**Comment by novysodope** [comment]
可以了，试试看https://github.com/novysodope/fupo_for_yonyou/releases/tag/%231%E9%97%AE%E9%A2%98%E4%BC%98%E5%8C%96

**Comment by FeiNiao** [comment]
可以使用了，感谢师傅
